### ISSUE TITLE
ImportError: cannot import name '_get_field_description'

### ISSUE THREAD

**Issue by YanivP** [limdauto/drf_openapi#70] opened 2017-10-18 10:35 UTC
* DRF OpenAPI version: 1.0.0
* Python version: 3.5
* Operating System: OSX

### Description

Trying to implement DRF OpenAPI on a Python 3.5 django project.
Ran into error: ImportError: cannot import name '_get_field_description'
Requirements do not say anything about supported Python versions but I'm guessing now 3.6 is required.

EDIT:
Adding some additional version information:
openapi-codec==1.2.1
djangorestframework==3.5.3
django-rest-swagger==2.1.0

### What I Did

Followed instructions as described. 
Ran into trouble due to example using Python f-strings which are unsupported on Python 3.5 . 
Attempted to correct example to supported Python 3.5.
Ran into the error.

```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x107465a60>
Traceback (most recent call last):
  File "/Users/admin/Documents/GIT/virtualenvs/workflows/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/admin/Documents/GIT/virtualenvs/workflows/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/Users/admin/Documents/GIT/virtualenvs/workflows/lib/python3.5/site-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/admin/Documents/GIT/virtualenvs/workflows/lib/python3.5/site-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Users/admin/Documents/GIT/virtualenvs/workflows/lib/python3.5/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/admin/Documents/GIT/virtualenvs/workflows/lib/python3.5/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/Users/admin/Documents/GIT/virtualenvs/workflows/lib/python3.5/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/Users/admin/Documents/GIT/virtualenvs/workflows/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/admin/Documents/GIT/virtualenvs/workflows/lib/python3.5/site-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/admin/Documents/GIT/virtualenvs/workflows/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/admin/Documents/GIT/virtualenvs/workflows/lib/python3.5/site-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Users/admin/Documents/GIT/virtualenvs/workflows/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/admin/Documents/GIT/workflows_service/workflows/urls.py", line 18, in <module>
    from drf_openapi import urls
  File "/Users/admin/Documents/GIT/virtualenvs/workflows/lib/python3.5/site-packages/drf_openapi/urls.py", line 3, in <module>
    from drf_openapi.views import SchemaView
  File "/Users/admin/Documents/GIT/virtualenvs/workflows/lib/python3.5/site-packages/drf_openapi/views.py", line 6, in <module>
    from drf_openapi.codec import OpenAPIRenderer, SwaggerUIRenderer
  File "/Users/admin/Documents/GIT/virtualenvs/workflows/lib/python3.5/site-packages/drf_openapi/codec.py", line 12, in <module>
    from openapi_codec.encode import _get_links, _get_field_description
ImportError: cannot import name '_get_field_description'

```

**Comment by dnsdev** [comment] 2017-10-18 11:20
I can confirm, that Python 3.6 is not required; maybe to run the example. But this is only due to the format-string thing.
This looks like you are missing the openapi_codec python package. Please do a
```pip install openapi-codec``` with your virtual env pip.
You may also need the django rest framework (```pip install djangorestframework```) and the Swagger package (```pip install django-rest-swagger```).

**Comment by YanivP** [comment] 2017-10-18 12:05
Hi, 
I have openapi-codec==1.2.1, djangorestframework==3.5.3, django-rest-swagger==2.1.0 in my requirements.txt (and double checked that they're already installed). I see there's a new openapi-codec 1.3.2, is that required?

**Comment by dnsdev** [comment] 2017-10-19 18:13
Hey, I am not sure if this is really required but I also use 1.3.2. Maybe try this.
My current configuration for running drf_openapi is:
django-rest-swagger==2.1.2
djangorestframework==3.6.4
openapi-codec==1.3.2

**Comment by limdauto** [comment] 2017-12-17 18:44
This should have been fixed on the latest version.

**Closed by limdauto** 2017-12-17 18:44 UTC
